## server port
server:
  port: 9000

spring:
  main:
    allow-bean-definition-overriding: true

  h2:
    console:
      enabled: true
      path: /h2db

  datasource:
    driver-class-name: org.h2.Driver
    # url: jdbc:h2:~/db;AUTO_SERVER=TRUE
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    database: h2
    # hibernate.ddl-auto: create-drop
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

  # thymeleaf:
  #   check-template-location: true
  #   cache: false

  # 프로젝트 시작시 sql 초기화 설정
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

  # static file 기본 패스 설정 => resources
  web:
    resources:
      static-locations: classpath:/

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
logging:
  level:
    com:
      muca:
        web: debug
# springdoc:
#   default-consumes-media-type: application/json
#   default-produces-media-type: application/json
#   swagger-ui:
#     path: /swagger-ui.html
#     disable-swagger-default-url: true
#     # display-query-params-without-oauth2: true
